image: alpine:latest

before_script:
  - apt-get update
  - apt-get --yes --force-yes install rsync ssh

pages:
  stage: deploy
  script:
  - echo "${SSH_PRIVATE_KEY}" > id_rsa
  - chmod 400 id_rsa
  - mkdir "${HOME}/.ssh"
  - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
  - rsync -hrvz --delete --exclude='boom' --exclude='\..*' -e 'ssh -i id_rsa' * uav@tsunami.ocf.berkeley.edu:~/public_html/boom/ar/

  artifacts:
    paths:
    - public
  only:
  - master

